site_name: UniBe Azure Arc
repo_url: https://github.com/idsys-unibe-ch/azure-automation-scripts
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.instant
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Azure Arc:
    - Info: arc.md
    - Manuelle Installation:
      - Server in Azure Arc einbinden: server.md
      - SSH und AADSSH Erweiterung: aadsshextension.md
    - Automatisierung: automation.md
    - AADSSH Erweiterung Berechtigungen: aadrights.md
    - Verbinden mit Arc Server: connect.md
  - Az Client: azcli.md
  
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - def_list
  - tables
  - attr_list

  

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
