site_name: UniBe Azure Arc
repo_url: https://github.com/idsys-unibe-ch/azure-automation-scripts
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.instant
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
